"use client";
import { useEffect, useMemo, useState } from "react";
import { Database, RefreshCw, Search, SlidersHorizontal, Sparkles } from "lucide-react";

type Signal={id:string;source:string;platform?:string;date:string;text:string;topic:string;intent:string;sentiment:string;pain:string;engagement:number;tags:string[];humanStatus?:string};
export default function SignalsPage(){
 const [q,setQ]=useState("");const [topic,setTopic]=useState("All topics");const [signals,setSignals]=useState<Signal[]>([]);const [mode,setMode]=useState("");const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");const [analyzing,setAnalyzing]=useState(false);
 const load=()=>{setLoading(true);fetch(`/api/signals?limit=200`).then(r=>r.json()).then(d=>{setSignals(d.signals??[]);setMode(d.mode??"")}).finally(()=>setLoading(false))};
 useEffect(load,[]);
 const analyze=async()=>{setAnalyzing(true);const res=await fetch("/api/ai/tag-pending",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({limit:20})});const d=await res.json();setMessage(res.ok?`AI processed ${d.processed??0} observations · embedded ${d.embedded??0}`:(d.error??"AI analysis failed"));if(res.ok) await load();setAnalyzing(false);setTimeout(()=>setMessage(""),4000)};
 const rows=useMemo(()=>signals.filter(s=>(s.text+s.source+s.topic).toLowerCase().includes(q.toLowerCase())&&(topic==="All topics"||s.topic===topic)),[q,topic,signals]);
 const topics=["All topics",...Array.from(new Set(signals.map(s=>s.topic)))];
 return <div className="page">
  <div className="page-head"><div><div className="eyebrow">Persistent evidence browser</div><h1>Raw Signals</h1><div className="subhead">Every row is loaded from normalized observations when Supabase is configured; refreshing the page does not erase it.</div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button className="btn" onClick={load}><RefreshCw size={15}/> Reload database</button><button className="btn primary" disabled={analyzing||mode!=="supabase"} onClick={analyze}><Sparkles size={15}/> {analyzing?"Analyzing…":"Analyze 20 pending"}</button></div></div>
  <div className={`mode-banner ${mode==="supabase"?"good":"warn"}`}><Database size={18}/><div><b>{mode==="supabase"?"Reading persistent observations":"Demo dataset"}</b><span>{mode==="supabase"?" · PostgreSQL is the source of truth.":" · Configure Supabase to replace mock observations with your collected evidence."}</span></div></div>
  <div className="toolbar section-space"><div style={{position:"relative"}}><Search size={15} style={{position:"absolute",left:12,top:12,color:"#667085"}}/><input className="input" style={{paddingLeft:36}} placeholder="Search conversations..." value={q} onChange={e=>setQ(e.target.value)}/></div><select className="select" value={topic} onChange={e=>setTopic(e.target.value)}>{topics.map(t=><option key={t}>{t}</option>)}</select><button className="btn"><SlidersHorizontal size={15}/> More filters</button><span className="badge">{loading?"LOADING":`${rows.length} RESULTS`}</span></div>
  <div className="table-wrap"><table><thead><tr><th>Signal</th><th>Source</th><th>Topic / AI state</th><th>Intent</th><th>Pain</th><th>Engagement</th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td style={{minWidth:420}}><div className="mono">{s.id}</div><div style={{marginTop:5,fontWeight:650,lineHeight:1.45}}>{s.text}</div><div className="tag-row">{s.tags.map(t=><span className="badge purple" key={t}>{t}</span>)}</div></td><td><b>{s.source}</b><div className="row-meta">{s.platform??"source"} · {s.date}</div></td><td>{s.topic}</td><td>{s.intent}<div className="row-meta">{s.sentiment}</div></td><td><span className={`badge ${s.pain==="High"?"red":s.pain==="Medium"?"orange":""}`}>{s.pain}</span></td><td><b>{s.engagement}</b></td></tr>)}{!loading&&rows.length===0&&<tr><td colSpan={6}><div className="empty">No observations match this filter.</div></td></tr>}</tbody></table></div>
 {message&&<div className="toast">{message}</div>}
 </div>
}
