export default function SettingsPage(){return <div className="page">
 <div className="page-head"><div><div className="eyebrow">Configuration</div><h1>Settings</h1><div className="subhead">v0.4 keeps credentials server-side and makes the persistence/watch architecture explicit.</div></div></div>
 <div className="card">
  <div className="setting-row"><div><h3>Persistent data layer</h3><p>Supabase PostgreSQL is the source of truth; private Supabase Storage keeps immutable raw run snapshots. Demo mode uses browser storage only until these environment variables are configured.</p></div><div className="form-grid"><label>Database variables<input className="input" value="NEXT_PUBLIC_SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY" readOnly/></label><label>Raw bucket<input className="input" value="raw-data (private)" readOnly/></label></div></div>
  <div className="setting-row"><div><h3>Apify Facebook connector</h3><p>Provider-specific logic is isolated in the connector package. Start with a 20-post real-data validation before scaling.</p></div><div className="form-grid"><label>Actor ID<input className="input" defaultValue="apify/facebook-groups-scraper" readOnly/></label><label>Collection policy<select className="select" defaultValue="Incremental"><option>Incremental</option><option>Discovery</option><option>Targeted</option></select></label></div></div>
  <div className="setting-row"><div><h3>Watch scheduler</h3><p>Vercel Cron calls the Watch route hourly. Only due rules start a collection; the same cron also finalizes provider runs that completed while no browser was open.</p></div><div className="form-grid"><label>Cron route<input className="input" value="/api/cron/watch" readOnly/></label><label>Required secret<input className="input" value="CRON_SECRET" readOnly/></label></div></div>
  <div className="setting-row"><div><h3>AI analysis layer</h3><p>Tagging, embedding, Researcher and Challenger are durable downstream stages. Provider/model adapters are intentionally separate from acquisition.</p></div><div className="form-grid"><label>Model<input className="input" placeholder="Configure AI_MODEL in environment"/></label><label>Analysis policy<select className="select"><option>Evidence-first</option><option>Fast exploratory</option></select></label></div></div>
  <div className="setting-row"><div><h3>Privacy / access protection</h3><p>Author identifiers are hashed before normalized observations. Early deployments should be protected with Basic Auth until Supabase Auth + workspace RLS policies are implemented.</p></div><div className="form-grid"><label>PII handling<input className="input" value="Hash before analysis" readOnly/></label><label>Deployment gate<input className="input" value="APP_BASIC_AUTH_USER / PASSWORD" readOnly/></label></div></div>
 </div>
 </div>}
